# Generated by Django 3.0.9 on 2020-12-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_info',
            name='image',
            field=models.ImageField(blank=True, upload_to='enroll/images'),
        ),
    ]
