# Generated by Django 3.2.9 on 2022-03-14 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0003_auto_20201222_0721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_info',
            name='image',
        ),
    ]
